language: java
sudo: false
script: mvn clean install -Pembed
deploy:
  provider: releases
  api_key:
    secure: MbXoiI4a9ZiLqEyb93SGd1S4ZW/AfAChWQH8uu1WE9LBkcxRPEGc4LQKq0qMgxX60AKKk7Hw39MRL+1vUVOXVfwwx7IX1ECTbfpprjbPM7o77Km+lN5JR5rVVfiLC2zJySVG+OinofYQgmJ/n18yXcxIJFJHWfud04882jo90FNLAzuWEz9FSKe97Nf25VA9odtIMhcFgZAS0+Pu5waDMNpe0gt9oEjh7ARFZDbeAkX6RAQtp60V36MKf1aIKI3No11ZIxui0Sf6W8g07DPcSswNVuvXg/2dX3TJweTZlngDNbhgxRE5D0aUugmbIysgfPQ8DumGT7Mugfa7S7ZYJWvqRxhpm6r17HqWBys27C+PdlIKLP1E4shhSUOQd9VDCzmncfLGCfIs8GfxW6CLcmnLOO2bpSsfQLqV1SiF+ize+97byc2fHv3g7GsLNlWBY90CsKtd9viNh+IguVDcMKpPOd65w3HjzAcLLIgL0FRagx/szhaT4ExEIuJRRuqfRtWglt1EwFkL5JIrxRpfd2MLKph2ojTgefslvEQ+PbAw8/zS3fVtSUc8ybf/BrHuhl+gUviO1aBTlg2fWmHHtx/xihDRo2Dydb64I6cPJ4vhB/hidPPagqoyT8jmSgvB7YdpfuBoH9cM8+kYMzJR8uKJRkfbB5mnAuOaLm3iOUQ=
  file: relveo-service.jar
  on:
    repo: costalfy/relveo
